name: Shivanshu Tiwari Portfolio

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      # 1. Checkout your source code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build the Angular app
      - name: Build
        run: npm run build -- --base-href "https://frieden07.github.io/portfolio/"

      # 5. Deploy dist/ to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/shivanshu-portfolio/browser
          branch: gh-pages
          clean: true